name: cron_expression_descriptor
description: Dart library for describe cron expressions
version: 0.9.0
repository: https://github.com/jamalianpour/cron_expression_descriptor

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
